// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nhuurQYFkw6szZofLPv_BcYyM4BvDa4',
    appId: '1:925101813634:web:d1e8af7d456ecd07f3e99b',
    messagingSenderId: '925101813634',
    projectId: 'practiceimage-4dd0f',
    authDomain: 'practiceimage-4dd0f.firebaseapp.com',
    storageBucket: 'practiceimage-4dd0f.appspot.com',
    measurementId: 'G-DDBR7XCEJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCcg29AhLPN5_ZWjBSCK8P-EBMeJ4er2M',
    appId: '1:925101813634:android:b1cfc303c2db9274f3e99b',
    messagingSenderId: '925101813634',
    projectId: 'practiceimage-4dd0f',
    storageBucket: 'practiceimage-4dd0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ3VVKDGmchoBwDFuiuOkaj7XMnUusLmw',
    appId: '1:925101813634:ios:1f8864dc0e70e608f3e99b',
    messagingSenderId: '925101813634',
    projectId: 'practiceimage-4dd0f',
    storageBucket: 'practiceimage-4dd0f.appspot.com',
    iosClientId: '925101813634-lj4c7hp2e1griju3gk02bqc8tvinkrc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pratice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ3VVKDGmchoBwDFuiuOkaj7XMnUusLmw',
    appId: '1:925101813634:ios:cdbd692ff92101cff3e99b',
    messagingSenderId: '925101813634',
    projectId: 'practiceimage-4dd0f',
    storageBucket: 'practiceimage-4dd0f.appspot.com',
    iosClientId: '925101813634-aetol3psh7kceq63vvg6rbu61q62l1q5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pratice.RunnerTests',
  );
}
